### ISSUE TITLE
failed on addersJoined.split:: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by tx0c** [svelte-add/svelte-add#134]
```js
$ npm init @svelte-add/kit --with tailwindcss --tailwindcss-jit

➕ Svelte Add's SvelteKit app initializer (Version 2021.07.20.00)
file:///home/<user>/.npm/_npx/d3c1bcf667d04b7b/node_modules/@svelte-add/create-kit/cli.js:31
	const addersAndPresets = addersJoined.split("+");
	                                      ^

TypeError: Cannot read property 'split' of undefined
    at main (file:///home/<user>/.npm/_npx/d3c1bcf667d04b7b/node_modules/@svelte-add/create-kit/cli.js:31:40)
    at file:///home/<user>/.npm/_npx/d3c1bcf667d04b7b/node_modules/@svelte-add/create-kit/cli.js:162:1
```

**Comment by babichjacob** [comment]
Thank you for the report!
