### ISSUE TITLE
Cannot add supabase via command npx

### ISSUE THREAD

**Issue by careyestes** [svelte-add/svelte-add#136]
I sent this issue originally to the Supabase repo and was told to redirect it here.

From CL if I try:
npx apply https://github.com/joshnuss/svelte-supabase.git

I get:
```
CLI: npx apply joshnuss/svelte-supabase
usage: apply [-a magic] [-d] [-0123456789] command arguments ...
```

If I use npx svelte-add joshnuss/svelte-supabase, which is the syntax I use to install tailwind, I get the following:

```
npx: installed 61 in 7.163s
➕ Svelte Add (Version 2021.07.20.00)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

joshnuss/svelte-supabase
(node:57573) UnhandledPromiseRejectionWarning: Error: npx: installed 203 in 5.745s
npx: command not found: use-preset

    at Socket.<anonymous> (file:///Users/user/.npm/_npx/57573/lib/node_modules/svelte-add/index.js:465:11)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:57573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by babichjacob** [comment]
Try `npx use-preset joshnuss/svelte-supabase` (until / if the Supabase adder is rewritten built-in to `svelte-add`).

**Comment by joelepore** [comment]
> Try `npx use-preset joshnuss/svelte-supabase` (until / if the Supabase adder is rewritten built-in to `svelte-add`).

This worked for me, thanks.
