### ISSUE TITLE
Still format files when using `pnpx` rather than `npx`

### ISSUE THREAD

**Issue by delight** [svelte-add/svelte-add#159]
node --version: v16.13.0
pnpm --version 6.19.1
OS: Linux / bash

Steps:
```
pnpm init svelte@next tailwindplay
pnpx svelte-add@latest tailwindcss
```

Result:
```
pnpx svelte-add@latest tailwindcss
✔ Install the following package: svelte-add@latest? (Y/n) · true
Packages: +65
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/koko/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 65, reused 65, downloaded 0, added 65, done

/home/koko/.pnpm-store/v3/tmp/_npx/478250/5:
+ svelte-add 2021.10.1-0.2
➕ Svelte Add (Version 2021.10.10.02)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

PostCSS
/home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/index.js:12577
        throw new UndefinedParserError(`No parser could be inferred for file: ${rawOptions.filepath}`);
              ^

UndefinedParserError$1: No parser could be inferred for file: /home/koko/devel/js/svelte/tailwindcomponents/src/routes/__layout.svelte
    at normalize$1 (/home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/index.js:12577:15)
    at formatWithCursor$1 (/home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/index.js:14265:46)
    at /home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/index.js:59304:12
    at Object.format (/home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/index.js:59324:12)
    at updateFile (file:///home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/svelte-add@2021.10.1-0.2/node_modules/svelte-add/update.js:51:29)
    at async updateSvelte (file:///home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/svelte-add@2021.10.1-0.2/node_modules/svelte-add/update.js:216:2)
    at async setupStyleLanguage (file:///home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/svelte-add@2021.10.1-0.2/node_modules/svelte-add/adder-tools.js:201:3)
    at async run (file:///home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/svelte-add@2021.10.1-0.2/node_modules/svelte-add/adders/postcss/__run.js:34:2)
    at async runAdder (file:///home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/svelte-add@2021.10.1-0.2/node_modules/svelte-add/index.js:831:2)
    at async main (file:///home/koko/.pnpm-store/v3/tmp/_npx/478250/5/node_modules/.pnpm/svelte-add@2021.10.1-0.2/node_modules/svelte-add/cli.js:91:4)

```

**Comment by babichjacob** [comment]
This should no longer result in an error, but it also (probably) means the file won't be formatted for you automatically. I don't know enough to solve that.

**Comment by delight** [comment]
This is fixed already ... Please close!
