### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by maverick-dev-55** [svelte-add/svelte-add#170]
After running npm init @svelte-add/kit@latest i got this error:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:172:21)
    at updateFile (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:32:20)
    at async updateJson (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:169:2)
    at async install (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:836:4)
    at async run (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/adders/postcss/__run.js:66:2)
    at async runAdder (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:829:2)       
    at async setup (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/@svelte-add/app-initializer-tools/index.js:98:4)
    at async main (file:///C:/Users/RedRa/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/@svelte-add/create-kit/cli.js:5:2)   
npm ERR! code 1
npm ERR! path D:\Projects\svelte\musicapp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-kit

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RedRa\AppData\Local\npm-cache\_logs\2021-12-09T15_40_31_759Z-debug.loglogs\2021-12-09T15_40_31_759Z-debug.log
```
This is my Debug Log:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'init',
0 verbose cli   '@svelte-add/kit@latest'
0 verbose cli ]
1 info using npm@8.0.0
2 info using node@v16.11.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:C:\Users\RedRa\AppData\Roaming\nvm\v16.11.1\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:D:\Projects\svelte\musicapp\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\RedRa\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 3ms
14 timing config:load:global Completed in 3ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 22ms
19 timing npm:load:configload Completed in 22ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 7ms
23 timing npm:load:cleanupLog Completed in 7ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 41ms
27 http fetch GET 200 https://registry.npmjs.org/@svelte-add%2fcreate-kit 213ms (cache revalidated)
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 1ms
31 timing command:init Completed in 64162ms
32 verbose stack Error: command failed
32 verbose stack     at ChildProcess.<anonymous> (C:\Users\RedRa\AppData\Roaming\nvm\v16.11.1\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
32 verbose stack     at ChildProcess.emit (node:events:390:28)
32 verbose stack     at maybeClose (node:internal/child_process:1064:16)
32 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
33 verbose cwd D:\Projects\svelte\musicapp
34 verbose Windows_NT 10.0.19044
35 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init" "@svelte-add/kit@latest"
36 verbose node v16.11.1
37 verbose npm  v8.0.0
38 error code 1
39 error path D:\Projects\svelte\musicapp
40 error command failed
41 error command C:\WINDOWS\system32\cmd.exe /d /s /c create-kit
42 verbose exit 1
```
after running I went to check the folder and i only had postcss and svelte.config.cjs and src/app.css
also for more info here are the settings i entered
```
➕ Svelte Add's SvelteKit app initializer (Version 2021.11.27.00)
√ What directory should your app be created in? ... main-app
√ What scripting language will you write your app in? » JavaScript
√ What language will you write your app styles in? » PostCSS (used by Tailwind CSS)       
√ What framework will you use for your app's styles? » Tailwind CSS
√ Do you want to use Tailwind 3?
It is currently in alpha.
 » No
√ Do you want to install the Tailwind CSS Forms plugin?     
https://github.com/tailwindlabs/tailwindcss-forms
 » Yes
√ Do you want to install the Tailwind CSS Typography plugin?
https://github.com/tailwindlabs/tailwindcss-typography
 » Yes
√ What other features do you want for your app? »
√ What code quality tools do you want to help maintain your app? » ESLint, Prettier
√ Where will you deploy your app? » Nowhere (set up a deployment target later)
√ Do you want example and demonstration code added to your app to demonstrate how to use the tools you've selected? » Yes
√ Should your app's dependencies be installed with npm right now? » Yes
```

**Comment by babichjacob** [comment]
Thanks for the report. I am sorry you have experienced this because I don't quite know why it's happening. Follow discussion and progress on this at https://github.com/svelte-add/svelte-add/issues/162
