### ISSUE TITLE
pnpm peer dependency issue w/ tailwind

### ISSUE THREAD

**Issue by andykais** [svelte-add/svelte-add#177]
creating a fresh sveltekit repo (Skeleton app, Typescript support) gives a peer dependency error for postcss when initialized via pnpm and pnpx.

```bash
pnpm init svelte@next new-repo
cd new-repo
pnpx svelte-add@latest tailwindcss
pnpm i
```
during `pnpx svelte-add@latest tailwindcss`:
```

✔ Install the following package: svelte-add@latest? (Y/n) · true
Packages: +65
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/andrew/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 65, reused 65, downloaded 0, added 65, done

/Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5:
+ svelte-add 2022.1.0-5.0
➕ Svelte Add (Version 2022.01.05.00)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.
UndefinedParserError$1: No parser could be inferred for file: /Users/andrew/Code/scratchwork/my-repo/src/routes/__layout.svelte
    at normalize$1 (/Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/prettier@2.5.1/node_modules/prettier/index.js:13043:15)
    at formatWithCursor$1 (/Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/prettier@2.5.1/node_modules/prettier/index.js:14746:46)
    at /Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/prettier@2.5.1/node_modules/prettier/index.js:60959:12
    at Object.format (/Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/prettier@2.5.1/node_modules/prettier/index.js:60979:12)
    at updateFile (file:///Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/svelte-add@2022.1.0-5.0/node_modules/svelte-add/update.js:60:25)
    at async updateSvelte (file:///Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/svelte-add@2022.1.0-5.0/node_modules/svelte-add/update.js:227:2)
    at async setupStyleLanguage (file:///Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/svelte-add@2022.1.0-5.0/node_modules/svelte-add/adder-tools.js:199:3)
    at async run (file:///Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/svelte-add@2022.1.0-5.0/node_modules/svelte-add/adders/postcss/__run.js:46:2)
    at async runAdder (file:///Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/svelte-add@2022.1.0-5.0/node_modules/svelte-add/index.js:832:2)
    at async main (file:///Users/andrew/.pnpm-store/v3/tmp/_npx/71859/5/node_modules/.pnpm/svelte-add@2022.1.0-5.0/node_modules/svelte-add/cli.js:92:4)

PostCSS
 ✅ successfully set up and repaired (it looks like it was in a broken setup before this command was run)!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Tailwind CSS
 ✅ successfully set up!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Run pnpm install to install new dependencies, and then reload your IDE before starting your app.
```
during `pnpm i`:
```
 WARN  Issues with peer dependencies found
.
├─┬ svelte-check
│ └─┬ svelte-preprocess
│   └── ✕ missing peer postcss@"^7 || ^8"
├─┬ autoprefixer
│ └── ✕ missing peer postcss@^8.1.0
└─┬ tailwindcss
  ├── ✕ missing peer postcss@^8.0.9
  ├─┬ postcss-js
  │ └── ✕ missing peer postcss@^8.3.3
  └─┬ postcss-nested
    └── ✕ missing peer postcss@^8.2.14
Peer dependencies that should be installed:
  postcss@">=8.3.3 <9.0.0"
```

installing using npm and npx has no issues.
```bash
npm init svelte@next my-repo
cd my-repo
npx svelte-add@latest tailwindcss
npm i
```

(though `rm`'ing and reinstalling via `pnpm` gives the same peerp dependency error

**Comment by babichjacob** [comment]
These are warnings. We stopped installing `postcss` just to keep the dependency list shorter in https://github.com/svelte-add/postcss/commit/95a52a1aa05703448e618f086e6f1dd43e07d556

Your app functions the same without `postcss` installed because it's a dependency of Vite, whether or not you're using `pnpm`.

**Comment by andykais** [comment]
ah. And I guess because npm just flattens the dependency tree in node_modules, you dont see this error there. What about the `UndefinedParserError$1:`? Would the "explicit" way fo doing this be to re-add postcss as a dependency (rather than a peer dependency) to the warned deps above?

**Comment by babichjacob** [comment]
> What about the `UndefinedParserError$1:`?

This is because of https://github.com/svelte-add/svelte-add/issues/159. I don't think there's any value in showing this error because it causes confusion, so I'll hide it in a future update.

Similarly, I'll make the PostCSS adder install `postcss` again just so confusing warnings aren't shown (even though there is no functional impact).

**Comment by andykais** [comment]
great. Thanks for clearing that up! It is just a tad noisy as is

**Comment by babichjacob** [comment]
> > What about the `UndefinedParserError$1:`?
> 
> This is because of #159. I don't think there's any value in showing this error because it causes confusion, so I'll hide it in a future update.

Closed by https://github.com/svelte-add/svelte-add/commit/ae19aeafabee44290b2989ae56fe37dafe963e1e

> Similarly, I'll make the PostCSS adder install `postcss` again just so confusing warnings aren't shown (even though there is no functional impact).

Closed by https://github.com/svelte-add/postcss/commit/ce1df397a7464a876547ed4a21be07916cbd2275
