### ISSUE TITLE
[bug] Error: `plugins` in PostCSS config must be an array

### ISSUE THREAD

**Issue by yozachar** [svelte-add/svelte-add#201]
I already had SvelteKit (Vite) + TailwindCSS + DaisyUI set up manually (w/o using svelte-add). Nonetheless I ran `npx svelte-add tailwindcss` and this was the output:

```dart
Need to install the following packages:
  svelte-add
Ok to proceed? (y) y
➕ Svelte Add (Version 2022.02.14.00)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

Tailwind CSS
 ✅ already set up! skipping.
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

PostCSS
file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/adders/postcss/__run.js:30
        if (pluginsList.type !== "ArrayExpression") throw new Error("`plugins` in PostCSS config must be an array");
                                                          ^

Error: `plugins` in PostCSS config must be an array
    at updatePostcssConfig (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/adders/postcss/__run.js:30:52)
    at script (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/adders/postcss/__run.js:73:23)
    at content (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/update.js:140:22)
    at updateFile (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/update.js:36:20)
    at async updateJavaScript (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/update.js:135:2)
    at async run (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/adders/postcss/__run.js:69:2)
    at async runAdder (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:846:2)
    at async main (file:///home/user/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/cli.js:92:4)
```

```
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.
```

Makes it feel like, this was expected.

**Comment by babichjacob** [comment]
You're right, we could update `svelte-add` to accommodate object syntax for plugins in the PostCSS config.

**Comment by pashute** [comment]
Jan 1 2024:  Same bug when I do:
```npx svelte-add@latest tailwindcss```
according to https://www.skeleton.dev/docs/get-started

**Comment by davidtrattnig** [comment]
Jan 6th 2024: Same bug as above.

**Comment by ceifa** [comment]
Also where is the daisyui option? Is it gone???

**Comment by manuel3108** [comment]
DaisyUi option is indeed gone since the full rewrite. 

Since the last report of this issue, `svelte-add` has been completely rewritten. This exception no longer exists in the code. If you still encounter this problem, please add a comment, and I will re-open the issue. However, I find it unlikely at this point.
