### ISSUE TITLE
`pnpm create @svelte-add/vite` calls itself instead of the official `create-vite`

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#211]
Both binaries are called `create-vite`, so the wrong one is called. 

This is what the error can look like (Windows 11 with pnpm 7.3.0 and Node 18.4.0):

```
PS C:\Users\Jacob\Repositories> pnpm create @svelte-add/vite@latest my-new-vite-app                                          
.../Local/pnpm/store/v3/tmp/dlx-18576    |  +64 ++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\Jacob\AppData\Local\pnpm\store\v3
  Virtual store is at:             ../AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm
.../Local/pnpm/store/v3/tmp/dlx-18576    | Progress: resolved 64, reused 64, downloaded 0, added 64, done
➕ Svelte Add's Vite-powered Svelte app initializer (Version 2022.05.24.01)
🌒  Running the official Vite-powered Svelte app initializer...file:///C:/Users/Jacob/AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm/svelte-add@2022.5.2-4.1/node_modules/svelte-add/index.js:919
                        if (code !== 0) reject(new Error(body));
                                               ^

Error: ➕ Svelte Add's Vite-powered Svelte app initializer (Version 2022.05.24.01)
file:///C:/Users/Jacob/AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm/svelte-add@2022.5.2-4.1/node_modules/svelte-add/index.js:240
                if (remainingArgs.length !== 0) throw new Error(`${inspect(passedArgsCopy)} were passed as arguments but none of the adders specified (${inspect(passedFeatures)}), nor svelte-add itself, expected them, so they won't be used. Try running the command again without them.`);
                                                      ^

Error: { template: 'svelte' } were passed as arguments but none of the adders specified (undefined), nor svelte-add itself, expected them, so they won't be used. Try running the command again without them.
    at getChoices (file:///C:/Users/Jacob/AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm/svelte-add@2022.5.2-4.1/node_modules/svelte-add/index.js:240:41)
    at async setup (file:///C:/Users/Jacob/AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm/@svelte-add+app-initializer-tools@2022.5.2-4.1/node_modules/@svelte-add/app-initializer-tools/index.js:65:177)
    at async main (file:///C:/Users/Jacob/AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm/@svelte-add+create-vite@2022.5.2-4.1/node_modules/@svelte-add/create-vite/cli.js:6:2)

Node.js v18.4.0
npm ERR! code 1
npm ERR! path C:\Users\Jacob\Repositories
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-vite "my-new-vite-app" "--template" "svelte"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jacob\AppData\Local\npm-cache\_logs\2022-06-21T20_04_27_358Z-debug-0.log

    at ChildProcess.<anonymous> (file:///C:/Users/Jacob/AppData/Local/pnpm/store/v3/tmp/dlx-18576/node_modules/.pnpm/svelte-add@2022.5.2-4.1/node_modules/svelte-add/index.js:919:27)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Node.js v18.4.0
 ERROR  Command failed with exit code 1: C:\Users\Jacob\AppData\Local\pnpm\store\v3\tmp\dlx-18576\node_modules\.bin\create-vite.CMD my-new-vite-app
```

**Comment by babichjacob** [comment]
I don't know if this is a `pnpm` bug, and whether or not it is, if `@svelte-add/create-vite` can be fixed to work around it.

**Comment by manuel3108** [comment]
This does not seem to be happening anymore
