### ISSUE TITLE
Not able to run playwright test after installing npx svelte-add@latest tailwindcss on SvelteKit

### ISSUE THREAD

**Issue by shinokada** [svelte-add/svelte-add#226]
After adding tailwindcss, I get an error when I run `npm run test`:

```
❯ npm run test

> flowbite-svelte-blocks-3@0.0.1 test
> playwright test

(node:73123) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 1 test using 1 worker

[WebServer] (node:73125) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] (node:73126) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] (node:73126) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
[WebServer] [vite:css] Failed to load PostCSS config (searchPath: /Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3): [ReferenceError] require is not defined in ES module scope, you can use import instead
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/postcss.config.cjs:1:21
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at importDefault (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:25930:18)
    at Object.search (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:18367:38)
    at resolvePostcssConfig (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:42395:22)
    at compileCSS (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:42163:27)
    at Object.transform (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:41786:55)
    at transform (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:21911:16)
    at ModuleLoader.addModuleSource (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:22136:30)
file: /Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-3/src/app.css
error during build:

Error: Process from config.webServer was not able to start. Exit code: 1
```

## How to produce

```
npm init svelte@next my-app
cd my-app
pnpm i
npx svelte-add@latest tailwindcss
pnpm i
npm run test
```

**Comment by babichjacob** [comment]
Closing to keep discussion in https://github.com/sveltejs/kit/issues/5842 - resolution posted in https://github.com/sveltejs/kit/issues/5842#issuecomment-1207309336

**Comment by shinokada** [comment]
Node v0.16.16 works.

```
nvm install 0.16.16
nvm alias default 0.16.16
npm run test
```
