### ISSUE TITLE
Svelte Add's Vite initializer issue

### ISSUE THREAD

**Issue by offeex** [svelte-add/svelte-add#232]
```
√ What package manager should be used to install your app's dependencies right now? » None. I will install dependencies manually.
🌓  Running the official Vite-powered Svelte app initializer...file:///C:/Users/rocke/AppData/Local/pnpm/store/v3/tmp/dlx-9660/node_modules/.pnpm/svelte-add@2022.8.1-5.2/node_modules/svelte-add/index.js:919
                        if (code !== 0) reject(new Error(body));
                                               ^

Error:  ERROR   ERROR  Unknown option: 'yes'
For help, run: pnpm help init

    at ChildProcess.<anonymous> (file:///C:/Users/rocke/AppData/Local/pnpm/store/v3/tmp/dlx-9660/node_modules/.pnpm/svelte-add@2022.8.1-5.2/node_modules/svelte-add/index.js:919:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
 ERROR  Command failed with exit code 1: C:\Users\rocke\AppData\Local\pnpm\store\v3\tmp\dlx-9660\node_modules\.bin\create-vite.CMD

pnpm: Command failed with exit code 1: C:\Users\rocke\AppData\Local\pnpm\store\v3\tmp\dlx-9660\node_modules\.bin\create-vite.CMD
    at makeError (C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:22148:17)
    at handlePromise (C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:22719:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:184004:7)
    at async C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:192493:21
    at async run (C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:192467:34)
    at async runPnpm (C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:192685:5)
    at async C:\Users\rocke\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:192677:7
```

**Comment by manuel3108** [comment]
I cannot reproduce that anymore.
