### ISSUE TITLE
scss and ie. bootstrap fails to build with svelte-ts

### ISSUE THREAD

**Issue by kac-** [svelte-add/svelte-add#233]
```
npm create vite@latest sv2
# choose svelte-ts
cd sv2
npx svelte-add@latest scss
npm install
npm run dev
...
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
12:30:52 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /tmp/sv2/src/App.svelte
  2  |    import svelteLogo from './assets/svelte.svg'
  3  |    import Counter from './lib/Counter.svelte'
  4  |  </script>
     |           ^
  5  |  
  6  |  <main>
      at formatError (file:///tmp/sv2/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
      at TransformContext.error (file:///tmp/sv2/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
      at TransformContext.transform (file:///tmp/sv2/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40190:22)
      at async Object.transform (file:///tmp/sv2/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
      at async loadAndTransform (file:///tmp/sv2/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:29)
```

Diff between `svelte-ts` and `svelte` projects

```diff
Common subdirectories: sv1/.vscode and sv2/.vscode
diff '--color=auto' sv1/README.md sv2/README.md
1c1
< # Svelte + Vite
---
> # Svelte + TS + Vite
3c3
< This template should help get you started developing with Svelte in Vite.
---
> This template should help get you started developing with Svelte and TypeScript in Vite.
21c21
< This template contains as little as possible to get started with Vite + Svelte, while taking into account the developer experience with regards to HMR and intellisense. It demonstrates capabilities on par with the other `create-vite` templates and is a good starting point for beginners dipping their toes into a Vite + Svelte project.
---
> This template contains as little as possible to get started with Vite + TypeScript + Svelte, while taking into account the developer experience with regards to HMR and intellisense. It demonstrates capabilities on par with the other `create-vite` templates and is a good starting point for beginners dipping their toes into a Vite + Svelte project.
33c33
< **Why enable `checkJs` in the JS template?**
---
> **Why enable `allowJs` in the TS template?**
35c35
< It is likely that most cases of changing variable types in runtime are likely to be accidental, rather than deliberate. This provides advanced typechecking out of the box. Should you like to take advantage of the dynamically-typed nature of JavaScript, it is trivial to change the configuration.
---
> While `allowJs: false` would indeed prevent the use of `.js` files in the project, it does not prevent the use of JavaScript syntax in `.svelte` files. In addition, it would force `checkJs: false`, bringing the worst of both worlds: not being able to guarantee the entire codebase is TypeScript, and also having worse typechecking for the existing JavaScript. In addition, there are valid use cases in which a mixed codebase may be relevant.
43,44c43,44
< ```js
< // store.js
---
> ```ts
> // store.ts
diff '--color=auto' sv1/index.html sv2/index.html
7c7
<     <title>Vite + Svelte</title>
---
>     <title>Vite + Svelte + TS</title>
11c11
<     <script type="module" src="/src/main.js"></script>
---
>     <script type="module" src="/src/main.ts"></script>
Only in sv1: jsconfig.json
Only in sv2: node_modules
Only in sv2: package-lock.json
diff '--color=auto' sv1/package.json sv2/package.json
2c2
<   "name": "sv1",
---
>   "name": "sv2",
9c9,10
<     "preview": "vite preview"
---
>     "preview": "vite preview",
>     "check": "svelte-check --tsconfig ./tsconfig.json"
12a14
>     "@tsconfig/svelte": "^3.0.0",
13a16,19
>     "svelte-check": "^2.8.0",
>     "svelte-preprocess": "^4.10.7",
>     "tslib": "^2.4.0",
>     "typescript": "^4.6.4",
15,16c21
<     "sass": "^1.53.0",
<     "svelte-preprocess": "^4.10.7"
---
>     "sass": "^1.53.0"
Common subdirectories: sv1/public and sv2/public
Common subdirectories: sv1/src and sv2/src
diff '--color=auto' sv1/svelte.config.js sv2/svelte.config.js
1c1
< import preprocess from "svelte-preprocess";
---
> import sveltePreprocess from "svelte-preprocess";
3c3,5
< const config = {
---
> export default {
>   // Consult https://github.com/sveltejs/svelte-preprocess
>   // for more information about preprocessors
5c7
<     preprocess({
---
>     sveltePreprocess({
12,13d13
< 
< export default config;
Only in sv2: tsconfig.json
Only in sv2: tsconfig.node.json
diff '--color=auto' sv1/vite.config.js sv2/vite.config.js
1,7c1
< import { defineConfig } from "vite";
< import { svelte } from "@sveltejs/vite-plugin-svelte";
< 
< // https://vitejs.dev/config/
< export default defineConfig({
<   plugins: [svelte()],
< 
---
> const config = {
15c9,11
< });
---
> };
> 
> export default config;
Only in sv2: vite.config.ts
```

**Comment by kac-** [comment]
Works fine with `vite.config.js` copied from plain `svelte` project.

**Comment by babichjacob** [comment]
Thanks for the information, and I'm sorry about this bug. I will close this in favor of #234 to keep discussion there
