### ISSUE TITLE
Not able to install Tailwindcss in Stackblitz

### ISSUE THREAD

**Issue by shinokada** [svelte-add/svelte-add#241]
I could install it before, but today I found it returns an error:

```
npx svelte-add@latest tailwindcss
⠋ Installing package
...
success Install finished in 3.201s

➕ Svelte Add (Version 2022.08.15.02)
SyntaxError: Unexpected token 'p', "npx svelte-"... is not valid JSON
    at JSON.parse (<anonymous>)
    at getFolderInfo (file://file:///home/.turbo/npx/ezyyI4/node_modules/svelte-add/index.js:647:19)
    at async Module.getChoices (file://file:///home/.turbo/npx/ezyyI4/node_modules/svelte-add/index.js:163:22)
    at async main (file://file:///home/.turbo/npx/ezyyI4/node_modules/svelte-add/cli.js:38:147)
```

**Comment by babichjacob** [comment]
What was the resolution to this?

**Comment by shinokada** [comment]
That was my fault. I pasted a code in a wrong place.
I'm sorry.
