### ISSUE TITLE
Seems to have broken a few hours ago

### ISSUE THREAD

**Issue by pjebs** [svelte-add/svelte-add#242]
```
npm create @svelte-add/kit@latest my-new-svelte-kit-app -- --with postcss+mdsvex 

➕ Svelte Add's SvelteKit app initializer (Version 2022.11.25.00)
🌒  Installing dependencies...file:///Users/pj/.npm/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:919
			if (code !== 0) reject(new Error(body));
			                       ^

Error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-new-svelte-kit-app@0.0.1
npm ERR! Found: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.581
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pj/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pj/.npm/_logs/2022-12-10T00_02_58_462Z-debug-0.log

    at ChildProcess.<anonymous> (file:///Users/pj/.npm/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:919:27)

```

**Comment by pjebs** [comment]
Same with this command:

```
npm create @svelte-add/kit@latest my-new-svelte-kit-app -- --with typescript+eslint+prettier

npm create @svelte-add/kit@latest my-new-svelte-kit-app -- --with typescript+eslint+prettier
➕ Svelte Add's SvelteKit app initializer (Version 2022.11.25.00)
🌑  Installing dependencies...file:///Users/pj/.npm/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:919
			if (code !== 0) reject(new Error(body));
			                       ^

Error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-new-svelte-kit-app@0.0.1
npm ERR! Found: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.581
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pj/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pj/.npm/_logs/2022-12-10T00_05_19_202Z-debug-0.log

    at ChildProcess.<anonymous> (file:///Users/pj/.npm/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:919:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! code 1
npm ERR! path /Users/pj/software/gswift-cli
npm ERR! command failed
npm ERR! command sh /var/folders/y4/sqmyfzbj1vxbg714rbfkv4480000gn/T/npx-4d191635.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pj/.npm/_logs/2022-12-10T00_05_18_156Z-debug-0.log



```

**Comment by pjebs** [comment]
@babichjacob See https://github.com/sveltejs/kit/issues/8048

**Comment by babichjacob** [comment]
@pjebs This might've been fixed now. Can you see if it was? Thanks.

**Comment by pjebs** [comment]
@babichjacob Still not fixed.

**Comment by pjebs** [comment]
```js
npm create @svelte-add/kit@latest my-new-svelte-kit-app -- --with typescript+eslint+prettier
➕ Svelte Add's SvelteKit app initializer (Version 2022.12.09.00)
🌒  Installing dependencies...file:///Users/pj/.npm/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:919
			if (code !== 0) reject(new Error(body));
			                       ^

Error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-new-svelte-kit-app@0.0.1
npm ERR! Found: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.581
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pj/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pj/.npm/_logs/2022-12-10T04_11_14_256Z-debug-0.log

    at ChildProcess.<anonymous> (file:///Users/pj/.npm/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:919:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! code 1
npm ERR! path /Users/pj/software/gswift-cli
npm ERR! command failed
npm ERR! command sh /var/folders/y4/sqmyfzbj1vxbg714rbfkv4480000gn/T/npx-989803d5.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pj/.npm/_logs/2022-12-10T04_11_13_166Z-debug-0.log
```

**Comment by benmccann** [comment]
> npm create @svelte-add/kit@latest my-new-svelte-kit-app -- --with typescript+eslint+prettier

I just ran this command and it succeeded for me

**Comment by pjebs** [comment]
@benmccann 
I just ran it too just now and it failed.

Can you check if you're running a cached copy. In the Latest commit, Vite was not even updated to v4 so it can't have worked.

**Comment by manuel3108** [comment]
I just ran it now with 2022.12.0-9.0 and it worked flawlessly
