### ISSUE TITLE
Unable to create project with postcss (@svelte-add/create-kit)

### ISSUE THREAD

**Issue by chadulous** [svelte-add/svelte-add#250]
```
 Svelte Add's Vite-powered Svelte app initializer (Version 2022.12.09.00)
✔ What directory should your app be created in? … .
✔ What scripting language will you write your app in? › TypeScript
✔ What language will you write your app styles in? › PostCSS (used by Tailwind CSS)
✔ Do you want to use Autoprefixer?
https://github.com/postcss/autoprefixer
 › No
✔ What framework will you use for your app's styles? › Tailwind CSS
✔ Do you want to use the Tailwind CSS Forms plugin?
https://github.com/tailwindlabs/tailwindcss-forms
 › No
✔ Do you want to use the Tailwind CSS Typography plugin?
https://github.com/tailwindlabs/tailwindcss-typography
 › No
✔ Do you want to use daisyUI?
It provides component classes for Tailwind CSS. https://daisyui.com/
 › No
✔ What other features do you want for your app? › 
✔ What code quality tools do you want to help maintain your app? › 
✔ Where will you deploy your app? › Nowhere (set up a deployment target later)
✔ Do you want example code added to your app to demonstrate how to use the tools you've selected? › No. Keep it completely minimal.
✔ What package manager should be used to install your app's dependencies right now? › npm

PostCSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/svelte-add/update.js:176:21)
    at updateFile (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/svelte-add/update.js:36:20)
    at async updateJson (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/svelte-add/update.js:173:2)
    at async install (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/svelte-add/index.js:852:4)
    at async run (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/svelte-add/adders/postcss/__run.js:90:2)
    at async runAdder (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/svelte-add/index.js:845:2)
    at async setup (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/@svelte-add/app-initializer-tools/index.js:125:4)
    at async main (file:///Users/maverickdev/.npm/_npx/200523a90639919a/node_modules/@svelte-add/create-vite/cli.js:6:2)

Node.js v18.7.0
npm ERR! code 1
npm ERR! path /Users/maverickdev/gemOS
npm ERR! command failed
npm ERR! command sh /var/folders/k9/zxdb1t150lv5lgq_ykwmyw4c0000gn/T/npx-41a1f60a.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maverickdev/.npm/_logs/2023-01-12T22_33_54_857Z-debug-0.log
```

**Comment by c0nscience** [comment]
```
$ npm create @svelte-add/vite@latest
➕ Svelte Add's Vite-powered Svelte app initializer (Version 2022.12.09.00)
√ What directory should your app be created in? ... frontend
√ What scripting language will you write your app in? » JavaScript
√ What language will you write your app styles in? » PostCSS (used by Tailwind CSS)
√ Do you want to use Autoprefixer?
https://github.com/postcss/autoprefixer
 » Yes
√ What framework will you use for your app's styles? » Tailwind CSS
√ Do you want to use the Tailwind CSS Forms plugin?
https://github.com/tailwindlabs/tailwindcss-forms
 » Yes
√ Do you want to use the Tailwind CSS Typography plugin?
https://github.com/tailwindlabs/tailwindcss-typography
 » Yes
√ Do you want to use daisyUI?
It provides component classes for Tailwind CSS. https://daisyui.com/
 » Yes
√ What other features do you want for your app? »
√ What code quality tools do you want to help maintain your app? »
√ Where will you deploy your app? » Nowhere (set up a deployment target later)
√ Do you want example code added to your app to demonstrate how to use the tools you've selected? » Yes
√ Should your app's dependencies be installed with npm right now? » No. I will install dependencies manually.

PostCSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:176:21)
    at updateFile (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:36:20)
    at async updateJson (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:173:2)
    at async install (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:852:4)
    at async run (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/adders/postcss/__run.js:90:2)
    at async runAdder (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:845:2)
    at async setup (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/@svelte-add/app-initializer-tools/index.js:125:4)
    at async main (file:///C:/Users/Benni/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/@svelte-add/create-vite/cli.js:6:2)

Node.js v18.14.0
npm ERR! code 1
npm ERR! path C:\Users\Benni\Documents\Projects\combat-helper
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-vite

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Benni\AppData\Local\npm-cache\_logs\2023-02-10T16_23_13_261Z-debug-0.log
```

I can confim the issue on windows 10 (git bash shell) any idea to fix this?

**Comment by manuel3108** [comment]
Are you still able to reproduce that? I just tried it locally, and everything seemed to be setup fine without any exception.

**Comment by nextgenthemes** [comment]
I just had this issue but with create vite. Try

`npm install svelte-preprocess@latest`

that fixed my issue for me.

Also try `npm outdated` and update packages to latest one by one and see if this fixes things. Be aware that this may actually break things. And it actually did for the Webpack build for me. You need to keep webpack-cli at 4.x

Sevelte tooling is unmaintained, broken and outdated all over the place. What a mess, what a shame. Literally everything you try is broken out of the box.

**Comment by manuel3108** [comment]
Hmmm, thats interesting. I tried this out a few times with different combinations, and wasn't able to reproduce that at all. I also tried it on git bash, which didn't bring up this error.

Couly you please provide me with the content `package.json` before and after the adder has run?

**Comment by manuel3108** [comment]
Please reopen this issue if this is still happening.

**Comment by TophC7** [comment]
This is happening to me as well, i have a completely clean install first time using node and i cant get it to create the starter project because of this

Tried in powshell and in wsl and with different node versions (18 and 21), not working in both environments.

```
PS C:\Users\Toph\Git> npm create @svelte-add/vite@latest
➕ Svelte Add's Vite-powered Svelte app initializer (Version 2023.09.170.00)
√ What directory should your app be created in? ... starter-svelte
√ What scripting language will you write your app in? » TypeScript
√ What language will you write your app styles in? » PostCSS (used by Tailwind CSS)
√ Do you want to use Autoprefixer?
https://github.com/postcss/autoprefixer
 » Yes
√ What framework will you use for your app's styles? » Tailwind CSS
√ Do you want to use the Tailwind CSS Forms plugin?
https://github.com/tailwindlabs/tailwindcss-forms
 » Yes
√ Do you want to use the Tailwind CSS Typography plugin?
https://github.com/tailwindlabs/tailwindcss-typography
 » No
√ Do you want to use daisyUI?
It provides component classes for Tailwind CSS. https://daisyui.com/
 » Yes
√ What other features do you want for your app? »
√ What code quality tools do you want to help maintain your app? » ESLint, Prettier
√ Where will you deploy your app? » Nowhere (set up a deployment target later)
√ Do you want example code added to your app to demonstrate how to use the tools you've selected? » No. Keep it completely minimal.
√ Should your app's dependencies be installed with npm right now? » Yes

PostCSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:176:21)
    at updateFile (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:36:20)
    at async updateJson (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:173:2)
    at async install (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:871:4)
    at async run (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/adders/postcss/__run.js:81:2)
    at async runAdder (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:864:2)
    at async setup (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/@svelte-add/app-initializer-tools/index.js:125:4)
    at async main (file:///C:/Users/Toph/AppData/Local/npm-cache/_npx/15062f9c027cdf86/node_modules/@svelte-add/create-vite/cli.js:6:2)

Node.js v21.1.0
npm ERR! code 1
npm ERR! path C:\Users\Toph\Git
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-vite

npm ERR! A complete log of this run can be found in: C:\Users\Toph\AppData\Local\npm-cache\_logs\2023-10-25T04_25_56_048Z-debug-0.log
```

The Log
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\Toph\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.2.1
2 info using node@v21.1.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\Toph\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\Toph\Git\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\Toph\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Toph\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm create @svelte-add/vite@latest
22 verbose argv "create" "@svelte-add/vite@latest"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:C:\Users\Toph\AppData\Local\npm-cache\_logs\2023-10-25T04_25_56_048Z-
26 verbose logfile C:\Users\Toph\AppData\Local\npm-cache\_logs\2023-10-25T04_25_56_048Z-debug-0.log
27 timing npm:load:logFile Completed in 9ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 37ms
31 silly logfile done cleaning log files
32 timing arborist:ctor Completed in 1ms
33 http fetch GET 200 https://registry.npmjs.org/@svelte-add%2fcreate-vite 909ms (cache revalidated)
34 timing arborist:ctor Completed in 0ms
35 timing arborist:ctor Completed in 0ms
36 timing command:create Completed in 37862ms
37 verbose stack Error: command failed
37 verbose stack     at ChildProcess.<anonymous> (C:\Users\Toph\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
37 verbose stack     at ChildProcess.emit (node:events:515:28)
37 verbose stack     at maybeClose (node:internal/child_process:1105:16)
37 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
38 verbose cwd C:\Users\Toph\Git
39 verbose Windows_NT 10.0.22621
40 verbose node v21.1.0
41 verbose npm  v10.2.1
42 error code 1
43 error path C:\Users\Toph\Git
44 error command failed
45 error command C:\WINDOWS\system32\cmd.exe /d /s /c create-vite
46 verbose exit 1
47 timing npm Completed in 38131ms
48 verbose code 1
49 error A complete log of this run can be found in: C:\Users\Toph\AppData\Local\npm-cache\_logs\2023-10-25T04_25_56_048Z-debug-0.log
```

**Comment by manuel3108** [comment]
If there is anyone else who is able to reproduce this, please let me know. I know this happened to me one time, but even in that case I didn't manage to reproduce it.

**Comment by gudata** [comment]
I was missing the ```.prettierrc``` file. when added the error changed :) 

Javascript is so fun !

**Comment by manuel3108** [comment]
Thanks for sharing! I will see if I can find a fix for that!

**Comment by manuel3108** [comment]
Looks like this error was produced by `svelte-add` core. `svelte-add` has been rewritten from the ground up, so this issue does not apply anymore.
