### ISSUE TITLE
Non-core adders were broken

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#26]

**Comment by secretgspot** [comment]
S D:\Dropbox\PROJECTS\WEB\_TEST\sveltekit-supabase> npx svelte-add joshnuss/svelte-supabase
C:\Users\mine\AppData\Local\npm-cache\_npx\76ab19934dff27c3\node_modules\svelte-add\cli.cjs:17
     default: return Promise.reject(new Error("Unknown variable dynamic import: " + path));
                                    ^

Error: Unknown variable dynamic import: ./modules/joshnuss/svelte-supabase/run.js
    at _variableDynamicImportRuntime0_ (C:\Users\mine\AppData\Local\npm-cache\_npx\76ab19934dff27c3\node_modules\svelte-add\cli.cjs:17:37)
    at main (C:\Users\mine\AppData\Local\npm-cache\_npx\76ab19934dff27c3\node_modules\svelte-add\cli.cjs:30:23)
    at Object.<anonymous> (C:\Users\mine\AppData\Local\npm-cache\_npx\76ab19934dff27c3\node_modules\svelte-add\cli.cjs:38:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
