### ISSUE TITLE
Could not clone svelte-add/tailwindcss on Windows 10

### ISSUE THREAD

**Issue by saschaseniuk** [svelte-add/svelte-add#27]
after the command npx svelte-add tailwindcss i´ll get the following error

`[ info ]  Applying preset svelte-add/tailwindcss.
[ error ]  Could not clone svelte-add/tailwindcss.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Object.action (C:\Users\SSeniuk\AppData\Roaming\npm-cache\_npx\7432\node_modules\svelte-add\node_modules\simple-git\src\lib\plugins\error-detection.plugin.js:30:33)
    at PluginStore.exec (C:\Users\SSeniuk\AppData\Roaming\npm-cache\_npx\7432\node_modules\svelte-add\node_modules\simple-git\src\lib\plugins\plugin-store.js:21:33)
    at C:\Users\SSeniuk\AppData\Roaming\npm-cache\_npx\7432\node_modules\svelte-add\node_modules\simple-git\src\lib\runners\git-executor-chain.js:92:45
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (C:\Users\SSeniuk\AppData\Roaming\npm-cache\_npx\7432\node_modules\svelte-add\node_modules\simple-git\src\lib\runners\git-executor-chain.js:90:16)
    at GitExecutorChain.<anonymous> (C:\Users\SSeniuk\AppData\Roaming\npm-cache\_npx\7432\node_modules\svelte-add\node_modules\simple-git\src\lib\runners\git-executor-chain.js:74:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\SSeniuk\AppData\Roaming\npm-cache\_npx\7432\node_modules\svelte-add\node_modules\simple-git\src\lib\runners\git-executor-chain.js:5:58)`
    
Node Version 14.16.0

**Comment by saschaseniuk** [comment]
That's exactly what I did. But with the previous posted error. Unfortunately the error message didn't help me to solve the problem.

**Comment by babichjacob** [comment]
I don't know what can be done to help right now -- because this is a `use-preset` error outside my control, which is going to be dropped from `svelte-add` in the near future.
