### ISSUE TITLE
Vite/Svelte initializer produces no files, and errors with any style processor, other features (mdsvex), example code, and deps install

### ISSUE THREAD

**Issue by JacksonBellinger** [svelte-add/svelte-add#309]
In a new directory, the svelte-add initializer doesn't work. Running `npm create vite@latest vite-svelte --template svelte` before `npx svelte-add@latest mdsvex` works as expected, however.
Also the log files the prompt says to check have a slightly different name, seems like they're being logged before being created at a different timestamp

### Vite/Svelte/CSS/ no example / no install deps
```
❯ npm create @svelte-add/vite@latest
➕ Svelte Add's Vite-powered Svelte app initializer (Version 2023.08.310.00)
✔ What directory should your app be created in? … vite-svelte //(tried with new dir name and empty dir)
✔ What scripting language will you write your app in? › JavaScript
✔ What language will you write your app styles in? › CSS
✔ What other features do you want for your app? ›
✔ What code quality tools do you want to help maintain your app? ›
✔ Where will you deploy your app? › Nowhere (set up a deployment target later)
✔ Do you want example code added to your app to demonstrate how to use the tools you've selected? › No. Keep it completely minimal.
✔ Should your app's dependencies be installed with npm right now? › No. I will install dependencies manually.
🪄 Your JavaScript + CSS Vite-powered Svelte app is ready!
  1. cd vite-svelte
  2. npm install
  3. Reload your IDE
  4. npm run dev -- --open  # start developing with a browser open
❯ ls vite-svelte
//nothing here
❯ ls  /home/user/.npm/_logs
2023-09-01T19_22_05_573Z-debug-0.log  2023-09-09T20_18_37_974Z-eresolve-report.txt
2023-09-01T19_22_37_134Z-debug-0.log  2023-09-10T17_13_06_914Z-debug-0.log
❯ cat /home/user/.npm/_logs/2023-09-10T17_13_06_914Z-debug-0.log
0 verbose cli /home/user/.nvm/versions/node/v20.5.1/bin/node /home/user/.nvm/versions/node/v20.5.1/bin/npm
1 info using npm@9.8.0
2 info using node@v20.5.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/user/.nvm/versions/node/v20.5.1/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/user/code/svelte-add/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/user/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/user/.nvm/versions/node/v20.5.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm create vite vite-svelte svelte
22 verbose argv "create" "vite" "vite-svelte" "--template" "svelte"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/user/.npm/_logs/2023-09-10T17_13_06_914Z-
26 verbose logfile /home/user/.npm/_logs/2023-09-10T17_13_06_914Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 27ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 3 files
33 silly logfile done cleaning log files
34 http fetch GET 200 https://registry.npmjs.org/create-vite 105ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 timing command:create Completed in 1737ms
38 verbose exit 0
39 timing npm Completed in 1865ms
40 info ok
```

### With example code + install deps
```
❯ npm create @svelte-add/vite@latest
➕ Svelte Add's Vite-powered Svelte app initializer (Version 2023.08.310.00)
✔ What directory should your app be created in? … vite-svelte
✔ What scripting language will you write your app in? › JavaScript
✔ What language will you write your app styles in? › CSS
✔ What other features do you want for your app? ›
✔ What code quality tools do you want to help maintain your app? ›
✔ Where will you deploy your app? › Nowhere (set up a deployment target later)
✔ Do you want example code added to your app to demonstrate how to use the tools you've selected? › Yes
✔ Should your app's dependencies be installed with npm right now? › Yes
🌖  Installing dependencies...file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:954
                        if (code !== 0) reject(new Error(body));
                                               ^

Error: npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/user/code/svelte-add/vite-svelte/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/user/code/svelte-add/vite-svelte/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2023-09-10T17_16_42_210Z-debug-0.log

    at ChildProcess.<anonymous> (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:954:27)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v20.5.1
npm ERR! code 1
npm ERR! path /home/user/code/svelte-add
npm ERR! command failed
npm ERR! command sh -c create-vite

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2023-09-10T17_16_23_286Z-debug-0.log
❯ cat /home/user/.npm/_logs/2023-09-10T17_16_42_210Z-debug-0.log
0 verbose cli /home/user/.nvm/versions/node/v20.5.1/bin/node /home/user/.nvm/versions/node/v20.5.1/bin/npm
1 info using npm@9.8.0
2 info using node@v20.5.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/user/.nvm/versions/node/v20.5.1/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/user/code/svelte-add/vite-svelte/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/user/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/user/.nvm/versions/node/v20.5.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install
22 verbose argv "install"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/user/.npm/_logs/2023-09-10T17_16_42_210Z-
26 verbose logfile /home/user/.npm/_logs/2023-09-10T17_16_42_210Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 26ms
31 timing config:load:flatten Completed in 1ms
32 timing arborist:ctor Completed in 1ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 1 files
35 timing idealTree:init Completed in 8ms
36 timing idealTree:userRequests Completed in 0ms
37 silly idealTree buildDeps
38 timing idealTree:#root Completed in 0ms
39 timing idealTree:buildDeps Completed in 0ms
40 timing idealTree:fixDepFlags Completed in 0ms
41 timing idealTree Completed in 10ms
42 timing reify:loadTrees Completed in 11ms
43 timing reify:diffTrees Completed in 0ms
44 silly reify moves {}
45 timing reify:retireShallow Completed in 0ms
46 timing reify:createSparse Completed in 0ms
47 timing reify:loadBundles Completed in 0ms
48 timing reify:unpack Completed in 0ms
49 timing reify:unretire Completed in 0ms
50 timing build:queue Completed in 0ms
51 timing build:deps Completed in 0ms
52 timing build Completed in 0ms
53 timing reify:build Completed in 0ms
54 timing reify:trash Completed in 0ms
55 silly logfile done cleaning log files
56 timing reify:save Completed in 1ms
57 timing reify Completed in 19ms
58 timing command:install Completed in 21ms
59 verbose stack Error: ENOENT: no such file or directory, open '/home/user/code/svelte-add/vite-svelte/package.json'
60 verbose cwd /home/user/code/svelte-add/vite-svelte
61 verbose Linux 5.15.90.1-microsoft-standard-WSL2
62 verbose node v20.5.1
63 verbose npm  v9.8.0
64 error code ENOENT
65 error syscall open
66 error path /home/user/code/svelte-add/vite-svelte/package.json
67 error errno -2
68 error enoent ENOENT: no such file or directory, open '/home/user/code/svelte-add/vite-svelte/package.json'
69 error enoent This is related to npm not being able to find a file.
69 error enoent
70 verbose exit -2
71 timing npm Completed in 149ms
72 verbose code -2
73 error A complete log of this run can be found in: /home/user/.npm/_logs/2023-09-10T17_16_42_210Z-debug-0.log
```

###With Mdsvex. gives the same result if I enable SCSS or ESLint / Prettier
```
❯ npm create @svelte-add/vite@latest
➕ Svelte Add's Vite-powered Svelte app initializer (Version 2023.08.310.00)
✔ What directory should your app be created in? … vite-svelte
✔ What scripting language will you write your app in? › JavaScript
✔ What language will you write your app styles in? › CSS
✔ What other features do you want for your app? › mdsvex
✔ What code quality tools do you want to help maintain your app? ›
✔ Where will you deploy your app? › Nowhere (set up a deployment target later)
✔ Do you want example code added to your app to demonstrate how to use the tools you've selected? › No. Keep it completely minimal.
✔ Should your app's dependencies be installed with npm right now? › No. I will install dependencies manually.

mdsvex
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:176:21)
    at updateFile (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:36:20)
    at async updateJson (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/update.js:173:2)
    at async install (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:871:4)
    at async run (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/adders/mdsvex/__run.js:282:2)
    at async runAdder (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/svelte-add/index.js:864:2)
    at async setup (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/@svelte-add/app-initializer-tools/index.js:125:4)
    at async main (file:///home/user/.npm/_npx/15062f9c027cdf86/node_modules/@svelte-add/create-vite/cli.js:6:2)

Node.js v20.5.1
npm ERR! code 1
npm ERR! path /home/user/code/vite-svelte-mdsvex-template
npm ERR! command failed
npm ERR! command sh -c create-vite

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2023-09-10T16_**58**_50_010Z-debug-0.log
❯ ls  /home/user/.npm/_logs/
...
2023-09-01T19_22_05_573Z-debug-0.log  2023-09-09T20_18_37_974Z-eresolve-report.txt
2023-09-01T19_22_37_134Z-debug-0.log  2023-09-10T16_**59**_13_561Z-debug-0.log
❯ cat /home/user/.npm/_logs/2023-09-10T16_59_13_561Z-debug-0.log
0 verbose cli /home/user/.nvm/versions/node/v20.5.1/bin/node /home/user/.nvm/versions/node/v20.5.1/bin/npm
1 info using npm@9.8.0
2 info using node@v20.5.1
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/user/.nvm/versions/node/v20.5.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/user/code/vite-svelte-mdsvex-template/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/user/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/user/.nvm/versions/node/v20.5.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 8ms
17 timing npm:load:configload Completed in 8ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm create vite vite-svelte svelte
22 verbose argv "create" "vite" "vite-svelte" "--template" "svelte"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/user/.npm/_logs/2023-09-10T16_59_13_561Z-
26 verbose logfile /home/user/.npm/_logs/2023-09-10T16_59_13_561Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 27ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 3 files
33 silly logfile done cleaning log files
34 http fetch GET 200 https://registry.npmjs.org/create-vite 115ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 timing command:create Completed in 1735ms
38 verbose exit 0
39 timing npm Completed in 1865ms
40 info ok
```

**Comment by manuel3108** [comment]
@JacksonBellinger I just had a look at this and I am unable to reproduce this. Given exactly the same commands as you, everything got created for me (windows): 
![image](https://github.com/svelte-add/svelte-add/assets/30698007/3ac2418b-83cd-4f5e-bc4d-72b65cb77d29)

From what I can currently tell, it looks like this is a problem on your local machine. Did you try running this command in another machine, to see if we have a different behavior there?

Any further information would be highly appreciated.

**Comment by JacksonBellinger** [comment]
I'm on an ubuntu wsl, maybe that's it? I'll try it on something else
