### ISSUE TITLE
`bunx` and tailwindcss adder does not work (svelte-add@2.3.3, Windows)

### ISSUE THREAD

**Issue by fzn0x** [svelte-add/svelte-add#473]
### Topic

bunx, tailwindcss

### Version

2.3.3

### Expected behavior

Installed.

### Actual behavior

User@DESKTOP-69TAUPC MINGW64 /d/Projects/portofolio-v2 (master)
$ npx svelte-add@latest tailwindcss
Need to install the following packages:
svelte-add@2.3.3
Ok to proceed? (y) y
svelte-add version 2.3.3

┌  Welcome to Svelte Add!
file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/@svelte-add/ast-manipulation/build/index.js:215
  const properties = objectExpression.properties.filter((x) => x.type == "ObjectProperty");
                                                 ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.property (file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/@svelte-add/ast-manipulation/build/index.js:215:50)
    at parseSvelteConfigIntoWorkspace (file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:1883:29)
    at async populateWorkspaceDetails (file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:1873:3)
    at async executePlan (file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:15908:3)
    at async executeAdders (file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:15887:3)
    at async executeCli (file:///C:/Users/User/AppData/Local/npm-cache/_npx/583905104f230c6e/node_modules/svelte-add/build/index.js:63:3)

Node.js v18.20.2

User@DESKTOP-69TAUPC MINGW64 /d/Projects/portofolio-v2 (master)
$ bunx svelte-add@latest tailwindcss
error: Script not found "svelte-add@latest"

Includes node version.

**Comment by AdrianGonz97** [comment]
The stack trace doesn't indicate that this is particularly a bun or Windows issue. 

Can you provide your `svelte.config.js`? I'm suspecting that a variable declaration is occurring before the config declaration: `const config = { ... }`

**Comment by fzn0x** [comment]
Thanks for the fast response. @AdrianGonz97 

Yes it's correct there was a variable declaration.

```js
// Svelte config does not support TS imports, so we need to use globalThis
const highlighter = globalThis.highlighter;
```
