### ISSUE TITLE
`storybook@next` tests failing `Cannot find @storybook\svelte\package.json`

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#475]
### Topic

storybook

### Version

does not matter

### Expected behavior

Tests succeed, see #386, #393 

### Actual behavior

Tests are failing: https://github.com/svelte-add/svelte-add/actions/runs/9796203200/job/27050096201?pr=469

```
✔ Getting the correct version of 10 packages
- Installing Storybook dependencies
✔ Installing Storybook dependencies

     Error: Cannot find @storybook/svelte/package.json, Error: Cannot find module '@storybook/svelte/package.json'
Require stack:
- /home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs
- /home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at getRendererDir (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:60:11624)
    at templatePath (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:62:2146)
    at copyTemplateFiles (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:62:3340)
    at async baseGenerator (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:108:782)
    at async generator15 (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:133:3110)
    at async installStorybook (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:145:4887)
    at async doInitiate (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/storybook/dist/generate.cjs:155:894)
    at async withTelemetry (/home/runner/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/core/dist/core-server/index.cjs:188662:12)
```

**Comment by manuel3108** [comment]
Remote issue: https://github.com/storybookjs/storybook/issues/28474

We might consider swapping `--skip-install` with `--no-dev` for now, but even that is causing problems at this point (https://github.com/storybookjs/storybook/issues/28475).
