### ISSUE TITLE
`.prettierrc.cjs` file causes error (Unable to process '.prettierrc'. Reason: Unexpected EOF)

### ISSUE THREAD

**Issue by j-tai** [svelte-add/svelte-add#485]
### Topic

tailwindcss

### Version

2.3.5

### Expected behavior

Tailwindcss is added to the project

### Actual behavior

```
$ npx svelte-add@latest tailwindcss
svelte-add version 2.3.5

┌  Welcome to Svelte Add!
│
◇  Do you want to use typography plugin?
│  No
└  Unable to process '.prettierrc'. Reason: Unexpected EOF

Error: Unable to process '.prettierrc'. Reason: Unexpected EOF
    at createOrUpdateFiles (file:///home/jtai/.npm/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:2018:37)
    at async processInlineAdder (file:///home/jtai/.npm/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:16030:33)
    at async executePlan (file:///home/jtai/.npm/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:15994:28)
    at async executeAdders (file:///home/jtai/.npm/_npx/583905104f230c6e/node_modules/@svelte-add/core/build/internal.js:15918:5)
    at async executeCli (file:///home/jtai/.npm/_npx/583905104f230c6e/node_modules/svelte-add/build/index.js:63:3)
```

### Reproduce

1. `git clone https://git.jtai.ca/repro/svelte-add-1.git`
2. `cd svelte-add-1`
3. `npx svelte-add@latest tailwindcss`
4. Do you want to use typography plugin --- answer `No`

**Comment by manuel3108** [comment]
Thanks, great reproduction. I have created a PR #486.

This is fixed with the latest release.
