### ISSUE TITLE
"npx svelte-add postcss" (or tailwindcss) fails with "The configuration file could not be found"

### ISSUE THREAD

**Issue by danawoodman** [svelte-add/svelte-add#64]
On latest sveltekit, getting the following errors when trying to use svelte-add to add tailwindcss or postcss.

```shell
npx svelte-add tailwindcss --jit
Need to install the following packages:
  svelte-add
Ok to proceed? (y) y
[ info ]  Applying preset svelte-add/tailwindcss.
[ error ]  The configuration file could not be found (tried in /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/tmp-12200-fEh58kp9FH25).
```

This was [talked about in Discord](https://discord.com/channels/457912077277855764/819723698415599626/853825288713535498) but I could not find a ticket so I'm reporting here. Hopefully this is the right place to report!

System info:

```shell
npx envinfo --system --npmPackages svelte,rollup,webpack --binaries --browsers

  System:
    OS: macOS 11.2
    CPU: (8) arm64 Apple M1
    Memory: 84.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/fnm_multishells/9404_1623953947746/bin/node
    npm: 7.15.1 - /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/fnm_multishells/9404_1623953947746/bin/npm
  Browsers:
    Brave Browser: 91.1.25.72
    Chrome: 91.0.4472.106
    Safari: 14.0.3
  npmPackages:
    svelte: ^3.34.0 => 3.38.2 
```

```shell
npm ls
├── @sveltejs/kit@1.0.0-next.115
├── @typescript-eslint/eslint-plugin@4.27.0
├── @typescript-eslint/parser@4.27.0
├── eslint-config-prettier@8.3.0
├── eslint-plugin-svelte3@3.2.0
├── eslint@7.28.0
├── prettier-plugin-svelte@2.3.0
├── prettier@2.2.1
├── svelte-check@2.1.0
├── svelte-preprocess@4.7.3
├── svelte@3.38.2
├── tslib@2.3.0
└── typescript@4.3.3
```

Repro:

```shell
npm init svelte@next myapp
cd myapp
npm i
npx svelte-add tailwindcss --jit # or just npx svelte-add postcss
```

**Comment by babichjacob** [comment]
It sounds like `npx` is using an old version of the package (maybe because of an `npm audit` problem). Other people have reported problems that occur for the same reason. 

I do not know whether or not it works to do `npx svelte-add@latest` instead of just `npx svelte-add`, but try that and let me know if it does, please.

Otherwise, you can find the latest version of the package at https://github.com/svelte-add/svelte-add/tags and ensure `npx` uses it like `npx svelte-add@2021.06.15.01`

**Comment by danawoodman** [comment]
I will try `@latest` tomorrow 👍

**Comment by danawoodman** [comment]
@babichjacob it fails with both `@latest` and `@master`:

```shell
npx svelte-add tailwindcss@latest --jit

Need to install the following packages:
  svelte-add
Ok to proceed? (y) y
[ info ]  Applying preset svelte-add/tailwindcss@latest.
[ error ]  The latest branch does not exist in the remote repository.


npx svelte-add tailwindcss@master --jit

Need to install the following packages:
  svelte-add
Ok to proceed? (y) y
[ info ]  Applying preset svelte-add/tailwindcss@master.
[ error ]  The master branch does not exist in the remote repository.
```

However the same issue presents with `main`:

```shell
npx svelte-add tailwindcss@main --jit  
Need to install the following packages:
  svelte-add
Ok to proceed? (y) y
[ info ]  Applying preset svelte-add/tailwindcss@main.
[ error ]  The configuration file could not be found (tried in /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/tmp-27404-xg5N6fJ0rFqK).
```

`@2021.06.15.01` fails with `The 2021.06.15.01 branch does not exist in the remote repository.`

Is it expected this works with tags?

**Comment by babichjacob** [comment]
Those are not the right ways to write it:

`npx svelte-add@latest tailwindcss`

**Comment by danawoodman** [comment]
Whoops my bad. I'll try again

**Comment by danawoodman** [comment]
Looks like `@latest` works but with some curious warnings:

```shell
npx svelte-add@latest tailwindcss --jit
Need to install the following packages:
  svelte-add@latest
Ok to proceed? (y) y
➕ Svelte Add
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

postcss
 ✅ successfully set up!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

tailwindcss
 ✅ successfully set up!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.
```

**Comment by babichjacob** [comment]
That warning appears no matter what because this is an automated tool so if you modified the SvelteKit project template in an unexpected way before running it then it's possible it won't work.

That being said, I've removed the yellow coloring in 4ba4eecefcc9dc8e413129bdd7faecdd4c0ec644

Since there is no remaining problem, I'll close this issue, thanks!

**Comment by danawoodman** [comment]
Just for an FYI, this issue appears to be still occurring. With a recent Kit project using `npx svelte-add tailwindcss --jit` is causing the "configuration not found" error unless you use `@latest`. Haven't noticed this when using `npx` with other tools.

**Comment by danawoodman** [comment]
@babichjacob Following up with an updated report; this is still occurring with a brand new project and fresh `npm` with `v17.2.0`.

Of course, using `npx svelte-add@latest tailwindcss` is working as previously mentioned.

Also of note, the `--jit` flag is now throwing an error. I assume this is because it is now part of the default? Perhaps a warning could be displayed instead of a stack trace?

```
npx svelte-add@latest tailwindcss --jit
Need to install the following packages:
  svelte-add@latest
Ok to proceed? (y) y
➕ Svelte Add (Version 2021.12.11.03)
file:///Users/danawoodman/.npm/_npx/583905104f230c6e/node_modules/svelte-add/index.js:209
                                if (!(option in defaults)) throw new Error(`${inspect(option)} is not a valid option for the ${adder} adder: ${Object.keys(defaults).length === 0 ? "it doesn't accept any options." : `it accepts ${inspect(Object.keys(defaults))} as options.`}`);
                                                                 ^

Error: 'jit' is not a valid option for the tailwindcss adder: it accepts [ 'forms', 'typography' ] as options.
    at getChoices (file:///Users/danawoodman/.npm/_npx/583905104f230c6e/node_modules/svelte-add/index.js:209:38)
    at async main (file:///Users/danawoodman/.npm/_npx/583905104f230c6e/node_modules/svelte-add/cli.js:27:147)

Node.js v17.2.0
```
